version: "3"

services:
  softether-bridge:
    image: sammrai/softether-bridge:latest
    container_name: softether-bridge
    environment:
      - USERNAME=vpnname
      - PASSWORD=vpnpassword
      - PSK=vpnsecret
      - VPN_SERVER=your.vpn.server:5555