name: Create and publish a Docker image

on:
  push:
    branches:
      - "main"
      - "add_cifile"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        COMMIT_HASH=$(git rev-parse --short=7 HEAD)
        DOCKER_TAG=$DOCKERHUB_USERNAME/$GITHUB_REPOSITORY:$COMMIT_HASH
        DOCKER_LATEST_TAG=$DOCKERHUB_USERNAME/$GITHUB_REPOSITORY:latest
        docker build -t $DOCKER_TAG .
        docker tag $DOCKER_TAG $DOCKER_LATEST_TAG
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
        docker push $DOCKER_TAG
        docker push $DOCKER_LATEST_TAG